# Generated by Django 4.2.5 on 2023-10-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_post_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.rider'),
        ),
        migrations.AlterField(
            model_name='rider',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.driver'),
        ),
    ]
